envsec: ENC[AES256_GCM,data:tdv9b7bnQt51vw==,iv:g97or5R5HCGrNNZUKAvrtncH5tnDPsuALadIvCPolxc=,tag:ByjRtecQzs0BVpbAQihklw==,type:str]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2024-02-26T18:08:57Z'
    mac: ENC[AES256_GCM,data:ntwQ1cRAuusVgDCCLJUSdW+nYPgw/QH5wsUDfezLXmPr7sGNzh/ZBJPpsj7mzlB7ksepCnSjTHmqA02G6RXAsJdtgRM49uDjwJ4Hj+K+iJ8BQZ57HsEXhqbSL8uamuXa7sIpUH6N7kGQg51icFGjnfpAYGHEdVQJyk+IzGRVI9U=,iv:TMMe7FtRsekqYZ1ratRwPvY5Sw/op1xmFkjVf6V4EIM=,tag:7RgnzFHOW3Nq16XMYU12Jw==,type:str]
    pgp:
    -   created_at: '2024-02-26T14:33:09Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAyP/NAuofvCYAQv/TjcIZz2Jww0jJPeByv0Ttgg2ya0WZofvD6Fr6TC15BXo
            lctGpS8eam3lgyqC3f8IRzMEUZ+WIcmbwiaTC29R1e2gT8r/OFQRTpbEaU+zce9N
            /D7WiRDBFvpdBx5qXsidFHhxSda+PXDAq2KaeOuLMv97L3WOXA+JFVc7FMHEK7uG
            tOWMdDY7uTEtxZ5vmF+xWtMPeYXaj8Uhj3IMq7ZIbtIZgDR6z5FM6faajtXq/YmM
            X/vYCHatkaWsHps5cKhBHyuava8Bf5+TDDNuvgmfcIE2C0p+8wXP7d0NrSzDGs3t
            TslCB7oBFdsa5dfm41rpNadXQSfhDoQL7phLHtWuLL5E6A422DenGU0FF3+oCmS6
            zwpESTjlwF2SbptEGYwKzXeRCvuuyd6qukhcrQGXxFvjxd5RDrXev894K0gKCBf1
            DMafhvqYHOWKVg4sr6A6t6miCEY1HirLypt4xOzdijUI/SQlCfGIjzd7MKiTuUMk
            WPtZsDWYpJW7aNnw/yJH0l4BIAeLPX0SRwTkf4aSihps6FR7dHgL53PD5JhFoQlq
            UHyA4J6ECbOf+JenJmU82v2D6M7bYoipbuNktfq0SHxTGWrfTLJy6xY6r1p+3OED
            sX3+L9EOMwGn0119QxvW
            =C+rk
            -----END PGP MESSAGE-----
        fp: 7931F9D97E5C38EB45AF64153C81B8D5FCCD08EF
    unencrypted_suffix: _unencrypted
    version: 3.0.3
